export const LOCATION_OPTIONS = [
  { value: "", label: "" },
  { value: "Dublin", label: "Dublin" },
  { value: "san francisco", label: "San Francisco" },
  { value: "Berlin", label: "Berlin" },
  { value: "New York", label: "New York" },
  { value: "London", label: "London" },
  // Add other cities or locations as needed

  { value: "Birmingham", label: "Birmingham" },
  { value: "Manchester", label: "Manchester" },
  { value: "Glasgow", label: "Glasgow" },
  { value: "Liverpool", label: "Liverpool" },

  { value: "Hamburg", label: "Hamburg" },
  { value: "Munich", label: "Munich" },
  { value: "Cologne", label: "Cologne" },
  { value: "Frankfurt", label: "Frankfurt" },

  { value: "Madrid", label: "Madrid" },
  { value: "Barcelona", label: "Barcelona" },
  { value: "Valencia", label: "Valencia" },
  { value: "Seville", label: "Seville" },
  { value: "Zaragoza", label: "Zaragoza" },

  { value: "Rome", label: "Rome" },
  { value: "Milan", label: "Milan" },
  { value: "Naples", label: "Naples" },
  { value: "Turin", label: "Turin" },
  { value: "Palermo", label: "Palermo" },

  { value: "Paris", label: "Paris" },
  { value: "Marseille", label: "Marseille" },
  { value: "Lyon", label: "Lyon" },
  { value: "Toulouse", label: "Toulouse" },
  { value: "Nice", label: "Nice" },

  { value: "Cork", label: "Cork" },
  { value: "Galway", label: "Galway" },
  { value: "Limerick", label: "Limerick" },
  { value: "Belfast", label: "Belfast" },
  { value: "Derry", label: "Derry" },
  { value: "Waterford", label: "Waterford" },
  { value: "Drogheda", label: "Drogheda" },
  { value: "Dundalk", label: "Dundalk" },
  { value: "Sligo", label: "Sligo" },
  { value: "Kilkenny", label: "Kilkenny" },
  { value: "Wexford", label: "Wexford" },
  { value: "Athlone", label: "Athlone" },

  { value: "Amsterdam", label: "Amsterdam" },
  { value: "Rotterdam", label: "Rotterdam" },
  { value: "The Hague", label: "The Hague" },
  { value: "Utrecht", label: "Utrecht" },
  { value: "Eindhoven", label: "Eindhoven" },

  { value: "Brussels", label: "Brussels" },
  { value: "Antwerp", label: "Antwerp" },
  { value: "Ghent", label: "Ghent" },
  { value: "Charleroi", label: "Charleroi" },
  { value: "Liège", label: "Liège" },

  { value: "Stockholm", label: "Stockholm" },
  { value: "Gothenburg", label: "Gothenburg" },
  { value: "Malmö", label: "Malmö" },
  { value: "Uppsala", label: "Uppsala" },
  { value: "Västerås", label: "Västerås" },

  { value: "Zurich", label: "Zurich" },
  { value: "Geneva", label: "Geneva" },
  { value: "Basel", label: "Basel" },
  { value: "Bern", label: "Bern" },
  { value: "Lausanne", label: "Lausanne" },

  { value: "Athens", label: "Athens" },
  { value: "Thessaloniki", label: "Thessaloniki" },
  { value: "Patras", label: "Patras" },
  { value: "Heraklion", label: "Heraklion" },
  { value: "Larissa", label: "Larissa" },

  // US CITIES W/ STATES
  { value: "New York, NY", label: "New York, NY" },
  { value: "Los Angeles, CA", label: "Los Angeles, CA" },
  { value: "Chicago, IL", label: "Chicago, IL" },
  { value: "Houston, TX", label: "Houston, TX" },
  { value: "Phoenix, AZ", label: "Phoenix, AZ" },
  { value: "Philadelphia, PA", label: "Philadelphia, PA" },
  { value: "San Antonio, TX", label: "San Antonio, TX" },
  { value: "San Diego, CA", label: "San Diego, CA" },
  { value: "Dallas, TX", label: "Dallas, TX" },
  { value: "San-Jose, CA", label: "San Jose, CA" },
  { value: "Austin, TX", label: "Austin, TX" },
  { value: "Jacksonville, FL", label: "Jacksonville, FL" },
  { value: "Fort-Worth, TX", label: "Fort Worth, TX" },
  { value: "Columbus, OH", label: "Columbus, OH" },
  { value: "Charlotte, NC", label: "Charlotte, NC" },
  { value: "Indianapolis, IN", label: "Indianapolis, IN" },
  { value: "San-Francisco, CA", label: "San Francisco, CA" },
  { value: "Seattle, WA", label: "Seattle, WA" },
  { value: "Denver, CO", label: "Denver, CO" },
  { value: "Washington, D.C.", label: "Washington, D.C." },
  { value: "Boston, MA", label: "Boston, MA" },
  { value: "El-Paso, TX", label: "El Paso, TX" },
  { value: "Nashville, TN", label: "Nashville, TN" },
  { value: "Detroit, MI", label: "Detroit, MI" },
  { value: "Oklahoma City, OK", label: "Oklahoma City, OK" },
  { value: "Portland, OR", label: "Portland, OR" },
  { value: "Las Vegas, NV", label: "Las Vegas, NV" },
  { value: "Memphis, TN", label: "Memphis, TN" },
  { value: "Louisville, KY", label: "Louisville, KY" },
  { value: "Baltimore, MD", label: "Baltimore, MD" },
  { value: "Milwaukee, WI", label: "Milwaukee, WI" },
  { value: "Albuquerque, NM", label: "Albuquerque, NM" },
  { value: "Tucson, AZ", label: "Tucson, AZ" },
  { value: "Fresno, CA", label: "Fresno, CA" },
  { value: "Mesa, AZ", label: "Mesa, AZ" },
  { value: "Sacramento, CA", label: "Sacramento, CA" },
  { value: "Atlanta, GA", label: "Atlanta, GA" },
  { value: "Kansas-City, MO", label: "Kansas City, MO" },
  { value: "Miami, FL", label: "Miami, FL" },
  { value: "Raleigh, NC", label: "Raleigh, NC" },
  { value: "Omaha, NE", label: "Omaha, NE" },
  { value: "Long-Beach, CA", label: "Long Beach, CA" },
  { value: "Oakland, CA", label: "Oakland, CA" },
  { value: "Minneapolis, MN", label: "Minneapolis, MN" },
  { value: "Tulsa, OK", label: "Tulsa, OK" },
  { value: "Tampa, FL", label: "Tampa, FL" },
  { value: "Arlington, TX", label: "Arlington, TX" },

  //US CITIES W/ NO STATE ABREVIATIONS
  { value: "New York", label: "New York" },
  { value: "Los Angeles", label: "Los Angeles" },
  { value: "Chicago", label: "Chicago" },
  { value: "Houston", label: "Houston" },
  { value: "Phoenix", label: "Phoenix" },
  { value: "Philadelphia", label: "Philadelphia" },
  { value: "San Antonio", label: "San Antonio" },
  { value: "San Diego", label: "San Diego" },
  { value: "Dallas", label: "Dallas" },
  { value: "San Jose", label: "San Jose" },
  { value: "Austin", label: "Austin" },
  { value: "Jacksonville", label: "Jacksonville" },
  { value: "Fort Worth", label: "Fort Worth" },
  { value: "Columbus", label: "Columbus" },
  { value: "Charlotte", label: "Charlotte" },
  { value: "Indianapolis", label: "Indianapolis" },
  { value: "San Francisco", label: "San Francisco" },
  { value: "Seattle", label: "Seattle" },
  { value: "Denver", label: "Denver" },
  { value: "Washington, D.C.", label: "Washington, D.C." },
  { value: "Boston", label: "Boston" },
  { value: "El Paso", label: "El Paso" },
  { value: "Nashville", label: "Nashville" },
  { value: "Detroit", label: "Detroit" },
  { value: "Oklahoma City", label: "Oklahoma City" },
  { value: "Portland", label: "Portland" },
  { value: "Las Vegas", label: "Las Vegas" },
  { value: "Memphis", label: "Memphis" },
  { value: "Louisville", label: "Louisville" },
  { value: "Baltimore", label: "Baltimore" },
  { value: "Milwaukee", label: "Milwaukee" },
  { value: "Albuquerque", label: "Albuquerque" },
  { value: "Tucson", label: "Tucson" },
  { value: "Fresno", label: "Fresno" },
  { value: "Mesa", label: "Mesa" },
  { value: "Sacramento", label: "Sacramento" },
  { value: "Atlanta", label: "Atlanta" },
  { value: "Kansas City", label: "Kansas City" },
  { value: "Miami", label: "Miami" },
  { value: "Raleigh", label: "Raleigh" },
  { value: "Omaha", label: "Omaha" },
  { value: "Long Beach", label: "Long Beach" },
  { value: "Oakland", label: "Oakland" },
  { value: "Minneapolis", label: "Minneapolis" },
  { value: "Tulsa", label: "Tulsa" },
  { value: "Tampa", label: "Tampa" },
  { value: "Arlington", label: "Arlington" },

  //ASIAN CITIES
  { value: "Jakarta", label: "Jakarta" },
  { value: "Tokyo", label: "Tokyo" },
  { value: "Beijing", label: "Beijing" },
  { value: "Seoul", label: "Seoul" },
  { value: "Shanghai", label: "Shanghai" },
  { value: "Mumbai", label: "Mumbai" },
  { value: "Delhi", label: "Delhi" },
  { value: "Bangkok", label: "Bangkok" },
  { value: "Manila", label: "Manila" },
  { value: "Hanoi", label: "Hanoi" },
  { value: "Taipei", label: "Taipei" },
  { value: "Singapore", label: "Singapore" },
  { value: "Kuala Lumpur", label: "Kuala Lumpur" },
  { value: "Hong Kong", label: "Hong Kong" },
  { value: "Dubai", label: "Dubai" },
  { value: "Karachi", label: "Karachi" },
  { value: "Istanbul", label: "Istanbul" },
  { value: "Dhaka", label: "Dhaka" },
  { value: "Cairo", label: "Cairo" },
  { value: "Tehran", label: "Tehran" },
  { value: "Baghdad", label: "Baghdad" },

  //SOUTH AMERICAN CITIES
  { value: "Buenos Aires", label: "Buenos Aires" },
  { value: "Sao Paulo", label: "Sao Paulo" },
  { value: "Rio de Janeiro", label: "Rio de Janeiro" },
  { value: "Lima", label: "Lima" },
  { value: "Santiago", label: "Santiago" },
  { value: "Bogota", label: "Bogota" },
  { value: "Caracas", label: "Caracas" },
  { value: "Quito", label: "Quito" },
  { value: "La Paz", label: "La Paz" },
  { value: "Asuncion", label: "Asuncion" },
  { value: "Montevideo", label: "Montevideo" },
  { value: "Brasilia", label: "Brasilia" },
  { value: "Manaus", label: "Manaus" },
  { value: "Lima", label: "Lima" },
];
